new:
	arduino-cli sketch new MyFirstSketch

compile:
	arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi MyFirstSketch

upload:
	arduino-cli upload -p /dev/cu.usbmodem101 --fqbn arduino:renesas_uno:unor4wifi MyFirstSketch
