new:
	arduino-cli sketch new MyFirstSketch

compile:
	arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi MyFirstSketch

upload:
	arduino-cli upload -p /dev/cu.usbmodemF412FA9F9B282 --fqbn arduino:renesas_uno:unor4wifi MyFirstSketch
